create table cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), nome varchar(255), preco decimal(19,2), restaurante_id bigint, primary key (id)) engine=InnoDB;
create table restaurante (id bigint not null auto_increment, data_actualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), tx_frete decimal(19,2), cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
insert into cozinha (nome) values ('Tailandeza');
insert into cozinha (nome) values ('Indiana');
insert into cozinha (nome) values ('Mocambicana');
insert into estado (nome) values ('MG');
insert into estado (nome) values ('RJ');
insert into cidade (nome,estado_id) values ('Belo Horizonte',1);
insert into cidade (nome,estado_id) values ('Rio de Janeiro',2);
insert into restaurante (endereco_bairro,endereco_cep,endereco_logradouro,endereco_numero,nome,tx_frete,cozinha_id,endereco_cidade_id,data_actualizacao,data_cadastro) VALUES ('Centro', '38400-99', 'Rua Joao Pinheiro', '1000', 'Thai Gourmet', '24', '3', '1',utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete,cozinha_id,data_actualizacao,data_cadastro) values ('A3',10,1,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete, cozinha_id,data_actualizacao,data_cadastro) values ('Galaxy',12,2,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete,cozinha_id,data_actualizacao,data_cadastro) values ('KFC',7,3,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete, cozinha_id,data_actualizacao,data_cadastro) values ('Mundos',14,3,utc_timestamp,utc_timestamp);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Apas Universal para molhos', 'Apas', 50, 3);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Asas De Frango ', 'Wings', 175, 4);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'bifinhos com nata', 'Alacarte', 350, 2);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'PAo de alho', 'Entrada', 100, 2);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Pizza Ahla Portuguesa', 'Pizza', 450, 5);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Pedacos de frango Especial', 'Pedaco', 350, 4);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Rabo de Vaca Especial', 'Petisco', 620, 1);
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Cartao de Debito');
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Cartao de Debito');
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Dinheiro');
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,3);
create table cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), nome varchar(255), preco decimal(19,2), restaurante_id bigint, primary key (id)) engine=InnoDB;
create table restaurante (id bigint not null auto_increment, data_actualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), tx_frete decimal(19,2), cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
insert into cozinha (nome) values ('Tailandeza');
insert into cozinha (nome) values ('Indiana');
insert into cozinha (nome) values ('Mocambicana');
insert into estado (nome) values ('MG');
insert into estado (nome) values ('RJ');
insert into cidade (nome,estado_id) values ('Belo Horizonte',1);
insert into cidade (nome,estado_id) values ('Rio de Janeiro',2);
insert into restaurante (endereco_bairro,endereco_cep,endereco_logradouro,endereco_numero,nome,tx_frete,cozinha_id,endereco_cidade_id,data_actualizacao,data_cadastro) VALUES ('Centro', '38400-99', 'Rua Joao Pinheiro', '1000', 'Thai Gourmet', '24', '3', '1',utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete,cozinha_id,data_actualizacao,data_cadastro) values ('A3',10,1,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete, cozinha_id,data_actualizacao,data_cadastro) values ('Galaxy',12,2,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete,cozinha_id,data_actualizacao,data_cadastro) values ('KFC',7,3,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete, cozinha_id,data_actualizacao,data_cadastro) values ('Mundos',14,3,utc_timestamp,utc_timestamp);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Apas Universal para molhos', 'Apas', 50, 3);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Asas De Frango ', 'Wings', 175, 4);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'bifinhos com nata', 'Alacarte', 350, 2);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'PAo de alho', 'Entrada', 100, 2);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Pizza Ahla Portuguesa', 'Pizza', 450, 5);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Pedacos de frango Especial', 'Pedaco', 350, 4);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Rabo de Vaca Especial', 'Petisco', 620, 1);
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Cartao de Debito');
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Cartao de Debito');
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Dinheiro');
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,3);
create table cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), nome varchar(255), preco decimal(19,2), restaurante_id bigint, primary key (id)) engine=InnoDB;
create table restaurante (id bigint not null auto_increment, data_actualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), tx_frete decimal(19,2), cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
insert into cozinha (nome) values ('Tailandeza');
insert into cozinha (nome) values ('Indiana');
insert into cozinha (nome) values ('Mocambicana');
insert into estado (nome) values ('MG');
insert into estado (nome) values ('RJ');
insert into cidade (nome,estado_id) values ('Belo Horizonte',1);
insert into cidade (nome,estado_id) values ('Rio de Janeiro',2);
insert into restaurante (endereco_bairro,endereco_cep,endereco_logradouro,endereco_numero,nome,tx_frete,cozinha_id,endereco_cidade_id,data_actualizacao,data_cadastro) VALUES ('Centro', '38400-99', 'Rua Joao Pinheiro', '1000', 'Thai Gourmet', '24', '3', '1',utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete,cozinha_id,data_actualizacao,data_cadastro) values ('A3',10,1,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete, cozinha_id,data_actualizacao,data_cadastro) values ('Galaxy',12,2,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete,cozinha_id,data_actualizacao,data_cadastro) values ('KFC',7,3,utc_timestamp,utc_timestamp);
insert into restaurante (nome,tx_Frete, cozinha_id,data_actualizacao,data_cadastro) values ('Mundos',14,3,utc_timestamp,utc_timestamp);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Apas Universal para molhos', 'Apas', 50, 3);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Asas De Frango ', 'Wings', 175, 4);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'bifinhos com nata', 'Alacarte', 350, 2);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'PAo de alho', 'Entrada', 100, 2);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Pizza Ahla Portuguesa', 'Pizza', 450, 5);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Pedacos de frango Especial', 'Pedaco', 350, 4);
INSERT INTO produto (ativo, descricao, nome, preco, restaurante_id) VALUES (1,'Rabo de Vaca Especial', 'Petisco', 620, 1);
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Cartao de Debito');
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Cartao de Debito');
INSERT INTO `algafood`.`forma_pagamento` (`descricao`) VALUES ('Dinheiro');
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (1,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (2,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (3,3);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,1);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,2);
insert into restaurante_forma_pagamento (restaurante_id,forma_pagamento_id) values (4,3);
